print("Hello World0")
print("Hello World2")
print("Hello World3")
print("Hello World4")
print("Hello World5")
print("Hello World6")
print("Hello World7")
print("Hello World8")
print("Hello World9-1")

print("Hello World")